config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :activities
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#index"
  get "activities/stats", to: "activities#stats", as: "stats_activities"
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  def stats
    @total_calories = Activity.sum(&:calories)
    @total_duration = Activity.sum(&:duration)
  end
  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      if params[:id] == "stats"
        stats
        render "stats"
      else
        @activity = Activity.find(params[:id])
      end
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:title, :activity_type, :start, :duration, :calories)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>">
  <p>
    <strong>Title:</strong>
    <%= activity.title %>
  </p>

  <p>
    <strong>Activity type:</strong>
    <%= activity.activity_type %>
  </p>

  <p>
    <strong>Start:</strong>
    <%= activity.start %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= activity.duration %>
  </p>

  <p>
    <strong>Calories:</strong>
    <%= activity.calories %>
  </p>

</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :activity_type, style: "display: block" %>
    <%= form.text_field :activity_type %>
  </div>

  <div>
    <%= form.label :start, style: "display: block" %>
    <%= form.datetime_field :start %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.text_field :duration %>
  </div>

  <div>
    <%= form.label :calories, style: "display: block" %>
    <%= form.number_field :calories %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Show this activity", @activity %> |
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Activities</h1>

<div id="activities">
  <% @activities.each do |activity| %>
    <%= render activity %>
    <p>
      <%= link_to "Show this activity", activity %>
    </p>
  <% end %>
</div>

<%= link_to "New activity", new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @activity %>

<div>
  <%= link_to "Edit this activity", edit_activity_path(@activity) %> |
  <%= link_to "Back to activities", activities_path %>

  <%= button_to "Destroy this activity", @activity, method: :delete %>
</div>

app/views/activities/stats.html.erb
<h1>Stats</h1>

<div>Total calories: <%= @total_calories %> </div>
<br>
<div>Total duration: <%= @total_duration %> </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActivityTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>Welcome to activity-tracker</h1>

<% if user_signed_in? %>
    <div> Logged in as: <%= current_user.email %> </div>
    <%= link_to "Edit account settings", edit_user_registration_path %>
    <%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to "Sign in", new_user_session_path %><br>
    <%= link_to "Sign up", new_user_registration_path %>
<% end %>